server:
  port: 8090

logging:
  pattern:
    level: "%5p %mdc [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    io.r2dbc.postgresql.client.ReactorNettyClient: info

spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth-server.loca.lt/oauth2/jwks