server:
  port: 8080

spring:
  application:
    name: oauth-client
  security:
    oauth2:
      client:
        registration:
          navid-oidc:
            provider: spring
            client-id: navid
            client-secret: navid-pass
            authorization-grant-type: authorization_code
            redirect-uri: "https://auth-client.loca.lt/login/oauth2/code/{registrationId}"
            scope:
              - ACTUATOR_READ
              - ENDPOINT_READ
              - ENDPOINT_WRITE
              - ENDPOINT_DELETE
              - openid
              - profile
              - email
        provider:
          spring:
            issuer-uri: https://auth-server.loca.lt
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
